"""
Gemini AI intelligence routes (Phase 3).

One endpoint exposes the AI dashboard insight. All data collection and the Gemini
call happen server-side, so the API key never reaches the browser.
"""
from fastapi import APIRouter, HTTPException, Query
import logging

from app.services.ai_insight_service import get_dashboard_insights, gemini_configured
from app.config import settings

logger = logging.getLogger(__name__)
router = APIRouter(tags=["AI Intelligence"])


@router.get("/dashboard-insights", summary="AI climate intelligence for the dashboard (auto-loaded)")
async def dashboard_insights(
    refresh: bool = Query(False, description="Bypass the cache and regenerate the insight"),
):
    """
    Returns a compact AI insight generated by Gemini from the user's latest stored data.

    - Automatically uses the most recent profile, assessment, fingerprint, analytics,
      recommendations, scenario, transformation plan and available historical snapshots.
    - Cached per data-state signature: Gemini is only called again when stored data changes.
    - Never fails the dashboard: if Gemini is unavailable, a calculated insight is returned
      with status="unavailable"/"error" and source="calculated".
    """
    try:
        return await get_dashboard_insights(force=refresh)
    except Exception as exc:  # pragma: no cover - defensive
        logger.error(f"Dashboard AI insight failed: {exc}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"AI insight unavailable: {exc}")


@router.get("/dashboard-insights/", summary="AI dashboard insights (trailing slash alias)", include_in_schema=False)
async def dashboard_insights_slash(
    refresh: bool = Query(False, description="Bypass the cache and regenerate the insight"),
):
    return await dashboard_insights(refresh=refresh)


@router.get("/status", summary="AI layer status (is Gemini configured?)")
async def ai_status():
    return {
        "gemini_configured": gemini_configured(),
        "model": settings.GEMINI_MODEL,
        "cache_minutes": settings.AI_INSIGHT_CACHE_MINUTES,
        "note": "The Gemini API key is stored only in the backend environment, never in the browser.",
    }
