// Centralized realistic mock data for ClimaCred AI (Phase 1 Frontend)
// Prepared with exact schema matching Phase 2 FastAPI + MongoDB models.

import {
  BusinessProfile,
  ClimateAssessmentData,
  ClimateFingerprint,
  GreenSolution,
  TransformationPhaseItem,
  ImpactVerificationMetric,
  UserPreferences,
} from '../types';

export const INITIAL_BUSINESS_PROFILE: BusinessProfile = {
  name: 'ABC Textile Manufacturing Ltd.',
  industry: 'Textile',
  businessType: 'Fabric Dyeing & Garment Finishing',
  location: 'Tirupur Industrial Cluster, Tamil Nadu, India',
  employees: 145,
  workingDaysPerMonth: 26,
  productionVolume: '42,000 meters / month',
  operatingHoursPerDay: 16,
  businessSize: 'Medium',
  facilityAreaSqFt: 38000,
  contactEmail: 'operations@abctextiles.in',
  phone: '+91 98450 12890',
};

export const INITIAL_ASSESSMENT_DATA: ClimateAssessmentData = {
  energy: {
    monthlyElectricityKwh: 38500,
    monthlyElectricityBillInr: 346500, // ~8.9 INR/kWh
    dieselGeneratorHoursPerMonth: 64,
    generatorFuelLitresPerMonth: 1280,
    existingSolarCapacityKw: 0,
    energyEfficientEquipmentPercent: 28,
  },
  water: {
    monthlyWaterLitres: 480000, // 480 kL/mo
    waterSource: 'Groundwater / Borewell',
    waterRecyclingAvailable: false,
    rainwaterHarvesting: false,
    leakageFrequency: 'Monthly',
    wastewaterTreatment: 'Primary / Settling',
  },
  waste: {
    organicWasteKgPerMonth: 380,
    plasticWasteKgPerMonth: 950,
    paperWasteKgPerMonth: 420,
    industrialWasteKgPerMonth: 1850,
    textileMaterialWasteKgPerMonth: 3600,
    currentRecyclingPercent: 22,
    wasteSegregationPracticed: true,
  },
  emissions: {
    primaryFuel: 'Electricity Grid',
    monthlyDieselLitres: 1620,
    monthlyPetrolLitres: 240,
    monthlyNaturalGasKg: 0,
    mainEmissionSources: ['Boiler Combustion', 'Grid Electricity (Thermal Base)', 'Heavy Transport', 'Backup Genset'],
    airPollutionControlSystem: 'Basic Scrubber',
  },
  mobility: {
    deliveryVehiclesCount: 8,
    vehicleFuelType: 'Diesel',
    monthlyFleetFuelLitres: 1950,
    employeeCommuteMode: 'Two-Wheelers',
    evAdoptedPercent: 0,
  },
  greenPractices: {
    ledLighting: true,
    solarPanels: false,
    rainwaterHarvesting: false,
    waterRecycling: false,
    wasteSegregation: true,
    energyEfficientMachinery: false,
    evAdoption: false,
    sustainableMaterials: false,
  },
};

export const INITIAL_CLIMATE_FINGERPRINT: ClimateFingerprint = {
  overallScore: 58,
  scoreLabel: 'Transition Stage',
  benchmarkPercentile: 46,
  summaryNote:
    'Your business has significant improvement opportunities primarily in Water, Energy, and Waste management. Implementing targeted interventions can raise your Climate Readiness to 84+.',
  topImprovementDimensions: ['Water Management', 'Energy Efficiency', 'Waste Reduction'],
  dimensions: [
    {
      dimension: 'Energy',
      score: 52,
      impactLevel: 'High',
      currentStatus: 'High reliance on peak-hour thermal grid & diesel backup gensets',
      primaryCause: 'Older non-inverter dye motors, thermal heat losses, zero on-site solar',
      improvementOpportunity: 'Rooftop solar PPA, VFD motor retrofits, waste heat economizer',
      potentialReduction: '32% power reduction',
    },
    {
      dimension: 'Water',
      score: 44,
      impactLevel: 'Very High',
      currentStatus: '480,000 L/month borewell extraction with basic primary settling only',
      primaryCause: 'Single-pass rinsing baths, unmonitored pipe leakage, no closed-loop RO',
      improvementOpportunity: 'Zero Liquid Discharge (ZLD) RO recycling & digital ultrasonic leak sensors',
      potentialReduction: '65% freshwater reduction',
    },
    {
      dimension: 'Waste',
      score: 55,
      impactLevel: 'High',
      currentStatus: '3.6 tonnes of yarn/fabric scrap sent to low-value landfill brokers',
      primaryCause: 'Pattern cutting scrap margin and lack of circular upcycling vendor contracts',
      improvementOpportunity: 'Circular fiber downcycling partner program & automated fabric nesting software',
      potentialReduction: '48% landfill diversion',
    },
    {
      dimension: 'Emissions',
      score: 62,
      impactLevel: 'Moderate',
      currentStatus: '41.2 MT CO₂e / month Scope 1 & 2 combined emissions footprint',
      primaryCause: 'Grid emission factor (0.82 kg CO₂/kWh) + diesel boiler fuel',
      improvementOpportunity: 'Renewable power transition + biomass pellet boiler retrofit',
      potentialReduction: '52% Scope 1+2 emissions',
    },
    {
      dimension: 'Mobility',
      score: 64,
      impactLevel: 'Moderate',
      currentStatus: '8 diesel cargo vans used for intra-city textile hub runs',
      primaryCause: 'Legacy diesel fleet with 9.4 km/L fuel efficiency and zero telemetry',
      improvementOpportunity: 'Phased commercial 3W/4W EV fleet transition and route batching',
      potentialReduction: '35% logistics emissions',
    },
    {
      dimension: 'Operations',
      score: 70,
      impactLevel: 'Moderate',
      currentStatus: 'Manual paper logbooks for shift power tracking and maintenance logs',
      primaryCause: 'Lack of automated sub-metering IoT sensors at departmental line feeds',
      improvementOpportunity: 'IoT edge smart sub-metering on key motors and steam lines',
      potentialReduction: '14% unmetered wastage',
    },
  ],
};

export const GREEN_SOLUTIONS_LIBRARY: GreenSolution[] = [
  {
    id: 'sol-solar',
    title: 'Rooftop Solar PV System (75 kWp)',
    category: 'Energy',
    problemAddressed: 'High grid electricity bills and diesel genset running hours during peak daylight factory shifts.',
    shortDesc: 'Grid-tied rooftop solar system with smart net-metering and inverter telemetry.',
    investmentRange: '₹28,00,000 – ₹34,00,000',
    investmentMinInr: 2800000,
    investmentMaxInr: 3400000,
    potentialAnnualSavingsInr: 915000,
    potentialEnvironmentalImpact: '108,000 kWh clean power generated / year',
    estimatedPaybackPeriodYears: 3.2,
    implementationDifficulty: 'Medium',
    co2ReductionTonnesPerYear: 88.5,
    resourceReductionValue: '35% grid power offset',
    featured: true,
  },
  {
    id: 'sol-water-ro',
    title: 'Closed-Loop Water Recycling & Ultrafiltration',
    category: 'Water',
    problemAddressed: '480,000 L/mo borewell groundwater extraction with heavy rinsing bath effluent.',
    shortDesc: 'Multi-stage ultrafiltration with reverse osmosis to recycle 65% rinse water back into dye baths.',
    investmentRange: '₹22,00,000 – ₹29,00,000',
    investmentMinInr: 2200000,
    investmentMaxInr: 2900000,
    potentialAnnualSavingsInr: 640000,
    potentialEnvironmentalImpact: '3,740,000 Litres freshwater saved annually',
    estimatedPaybackPeriodYears: 3.8,
    implementationDifficulty: 'High',
    co2ReductionTonnesPerYear: 18.2,
    resourceReductionValue: '65% freshwater reduction',
    featured: true,
  },
  {
    id: 'sol-machinery-vfd',
    title: 'VFD & IE4 Super-Premium Motors Retrofit',
    category: 'Energy',
    problemAddressed: 'Legacy standard induction motors running continuously at fixed speeds with throttle dampers.',
    shortDesc: 'Replace standard motors on blowers, pumps, and spinning lines with IE4 motors and VFD variable frequency drives.',
    investmentRange: '₹9,50,000 – ₹13,00,000',
    investmentMinInr: 950000,
    investmentMaxInr: 1300000,
    potentialAnnualSavingsInr: 410000,
    potentialEnvironmentalImpact: '46,000 kWh electrical load saved annually',
    estimatedPaybackPeriodYears: 2.6,
    implementationDifficulty: 'Low',
    co2ReductionTonnesPerYear: 37.7,
    resourceReductionValue: '18% motor load reduction',
    featured: true,
  },
  {
    id: 'sol-leak-sensors',
    title: 'Smart Ultrasonic Water Leak & Flow Telemetry',
    category: 'Water',
    problemAddressed: 'Unnoticed underground joint leakages and overflow tanks wasting an estimated 35,000 L/month.',
    shortDesc: 'IoT ultrasonic clamp-on flow meters and smart alert valves at key distribution junctions.',
    investmentRange: '₹2,20,000 – ₹3,50,000',
    investmentMinInr: 220000,
    investmentMaxInr: 350000,
    potentialAnnualSavingsInr: 165000,
    potentialEnvironmentalImpact: '420,000 Litres water saved annually',
    estimatedPaybackPeriodYears: 1.6,
    implementationDifficulty: 'Low',
    co2ReductionTonnesPerYear: 4.1,
    resourceReductionValue: '9% total water saved',
    featured: false,
  },
  {
    id: 'sol-rainwater',
    title: 'Rooftop Rainwater Harvesting & Recharge Well',
    category: 'Water',
    problemAddressed: 'Runoff loss from 38,000 sq ft industrial shed roof during monsoon cycles.',
    shortDesc: 'Guttering conduits, multi-media sand filters, and a 120,000 L underground holding storage tank.',
    investmentRange: '₹4,50,000 – ₹6,00,000',
    investmentMinInr: 450000,
    investmentMaxInr: 600000,
    potentialAnnualSavingsInr: 190000,
    potentialEnvironmentalImpact: '980,000 Litres groundwater recharged / year',
    estimatedPaybackPeriodYears: 2.8,
    implementationDifficulty: 'Medium',
    co2ReductionTonnesPerYear: 5.6,
    resourceReductionValue: '20% seasonal water offset',
    featured: false,
  },
  {
    id: 'sol-waste-recovery',
    title: 'Textile Fabric Off-Cut Circular Recovery & Baling',
    category: 'Waste',
    problemAddressed: '3.6 tonnes of yarn & clipping scrap disposed via unorganized low-recovery channels.',
    shortDesc: 'Automated hydraulic sorting baler + tie-up with certified recycled yarn & acoustic panel manufacturers.',
    investmentRange: '₹3,80,000 – ₹5,20,000',
    investmentMinInr: 380000,
    investmentMaxInr: 520000,
    potentialAnnualSavingsInr: 320000,
    potentialEnvironmentalImpact: '28.5 tonnes landfill diversion annually',
    estimatedPaybackPeriodYears: 1.4,
    implementationDifficulty: 'Low',
    co2ReductionTonnesPerYear: 24.3,
    resourceReductionValue: '66% textile waste recovered',
    featured: true,
  },
  {
    id: 'sol-ev-fleet',
    title: 'Commercial EV Cargo Van Transition (Phase 1)',
    category: 'Mobility',
    problemAddressed: 'High diesel fuel consumption and tailpipe soot from intra-city dispatch vans.',
    shortDesc: 'Replace 4 diesel cargo vans with 3.5-ton commercial electric vans and install dual 11kW Type 2 chargers.',
    investmentRange: '₹18,00,000 – ₹24,00,000',
    investmentMinInr: 1800000,
    investmentMaxInr: 2400000,
    potentialAnnualSavingsInr: 480000,
    potentialEnvironmentalImpact: '9,200 Litres diesel avoided annually',
    estimatedPaybackPeriodYears: 4.2,
    implementationDifficulty: 'Medium',
    co2ReductionTonnesPerYear: 24.8,
    resourceReductionValue: '50% fleet diesel reduction',
    featured: false,
  },
  {
    id: 'sol-route-opt',
    title: 'AI Delivery Route Dispatch & Load Optimization',
    category: 'Mobility',
    problemAddressed: 'Sub-optimal delivery routing, half-empty return trips, and traffic idling.',
    shortDesc: 'SaaS dispatch software with algorithmic route grouping, vehicle load filling, and driver tracking.',
    investmentRange: '₹80,000 – ₹1,50,000',
    investmentMinInr: 80000,
    investmentMaxInr: 150000,
    potentialAnnualSavingsInr: 145000,
    potentialEnvironmentalImpact: '3,100 Litres fuel saved per year',
    estimatedPaybackPeriodYears: 0.8,
    implementationDifficulty: 'Low',
    co2ReductionTonnesPerYear: 8.3,
    resourceReductionValue: '16% transport fuel reduction',
    featured: false,
  },
  {
    id: 'sol-heat-recovery',
    title: 'Boiler Flue Gas Waste Heat Economizer',
    category: 'Energy',
    problemAddressed: 'Excessive heat loss in exhaust stack from process steam boilers.',
    shortDesc: 'Tube bundle heat exchanger pre-heating boiler feedwater from 28°C to 72°C using flue gases.',
    investmentRange: '₹6,50,000 – ₹8,50,000',
    investmentMinInr: 650000,
    investmentMaxInr: 850000,
    potentialAnnualSavingsInr: 295000,
    potentialEnvironmentalImpact: '7,400 Litres boiler fuel saved / year',
    estimatedPaybackPeriodYears: 2.5,
    implementationDifficulty: 'Medium',
    co2ReductionTonnesPerYear: 19.8,
    resourceReductionValue: '12% boiler fuel reduction',
    featured: false,
  },
  {
    id: 'sol-led-iot',
    title: 'High-Bay Smart Daylight-Linked LED Lighting',
    category: 'Operations',
    problemAddressed: 'Metal-halide fixtures operating at continuous full wattage regardless of ambient skylights.',
    shortDesc: '150W high-efficiency LED luminaires with ambient daylight photocell dimming in work halls.',
    investmentRange: '₹3,00,000 – ₹4,20,000',
    investmentMinInr: 300000,
    investmentMaxInr: 420000,
    potentialAnnualSavingsInr: 180000,
    potentialEnvironmentalImpact: '21,000 kWh saved annually',
    estimatedPaybackPeriodYears: 1.9,
    implementationDifficulty: 'Low',
    co2ReductionTonnesPerYear: 17.2,
    resourceReductionValue: '55% lighting power reduction',
    featured: false,
  },
];

export const INITIAL_TRANSFORMATION_PLAN: TransformationPhaseItem[] = [
  {
    id: 'tp-1',
    phase: 'Phase 1',
    phaseName: 'Immediate Low-Hanging Actions (Month 1-3)',
    action: 'Install Smart Ultrasonic Leak Sensors & Fix Distribution Valves',
    priority: 'High',
    estimatedCost: '₹2,50,000',
    expectedBenefit: 'Save 420,000 L water & ₹1,65,000 / year',
    timeframe: 'Month 1 - 2',
    status: 'In Progress',
    category: 'Water',
  },
  {
    id: 'tp-2',
    phase: 'Phase 1',
    phaseName: 'Immediate Low-Hanging Actions (Month 1-3)',
    action: 'Deploy AI Route Batching for Textile Dispatch Vans',
    priority: 'Medium',
    estimatedCost: '₹95,000',
    expectedBenefit: 'Reduce 3,100 L diesel & save ₹1,45,000 / year',
    timeframe: 'Month 2 - 3',
    status: 'Completed',
    category: 'Mobility',
  },
  {
    id: 'tp-3',
    phase: 'Phase 1',
    phaseName: 'Immediate Low-Hanging Actions (Month 1-3)',
    action: 'Setup Segregation & Off-Cut Baling with Certified Recyclers',
    priority: 'High',
    estimatedCost: '₹4,20,000',
    expectedBenefit: 'Divert 28.5 tonnes waste & earn ₹3,20,000 / year scrap revenue',
    timeframe: 'Month 3',
    status: 'Pending',
    category: 'Waste',
  },
  {
    id: 'tp-4',
    phase: 'Phase 2',
    phaseName: 'System Efficiency Improvements (Month 4-7)',
    action: 'VFD & IE4 Motor Retrofit on Main Dye Pumps and Air Blowers',
    priority: 'High',
    estimatedCost: '₹11,00,000',
    expectedBenefit: 'Cut 46,000 kWh/yr load & save ₹4,10,000 / year',
    timeframe: 'Month 4 - 6',
    status: 'Pending',
    category: 'Energy',
  },
  {
    id: 'tp-5',
    phase: 'Phase 2',
    phaseName: 'System Efficiency Improvements (Month 4-7)',
    action: 'Install Flue Gas Economizer on Main Process Steam Boiler',
    priority: 'Medium',
    estimatedCost: '₹7,50,000',
    expectedBenefit: 'Pre-heat boiler feed to 72°C, cut fuel by 12%',
    timeframe: 'Month 6 - 7',
    status: 'Pending',
    category: 'Emissions',
  },
  {
    id: 'tp-6',
    phase: 'Phase 3',
    phaseName: 'Capital Green Investments (Month 8-14)',
    action: 'Commission 75 kWp Grid-Tied Rooftop Solar PV Installation',
    priority: 'High',
    estimatedCost: '₹31,00,000',
    expectedBenefit: 'Generate 108,000 clean kWh & save ₹9,15,000 / year',
    timeframe: 'Month 8 - 11',
    status: 'Pending',
    category: 'Energy',
  },
  {
    id: 'tp-7',
    phase: 'Phase 3',
    phaseName: 'Capital Green Investments (Month 8-14)',
    action: 'Closed-Loop Ultrafiltration & RO Water Recycling Plant',
    priority: 'High',
    estimatedCost: '₹26,00,000',
    expectedBenefit: 'Recycle 65% rinse water (3.74M L/yr) and slash borewell use',
    timeframe: 'Month 11 - 14',
    status: 'Pending',
    category: 'Water',
  },
  {
    id: 'tp-8',
    phase: 'Phase 4',
    phaseName: 'Impact Verification & Continuous Intelligence (Month 15+)',
    action: 'IoT Sub-Meter Telemetry Calibration & Third-Party Audit Verification',
    priority: 'Medium',
    estimatedCost: '₹1,80,000',
    expectedBenefit: 'Validate 225+ MT annual CO₂ reduction for ESG compliance & buyer audits',
    timeframe: 'Month 15 onwards',
    status: 'Pending',
    category: 'Operations',
  },
];

export const INITIAL_IMPACT_VERIFICATION: ImpactVerificationMetric[] = [
  {
    id: 'imp-energy',
    name: 'Grid Electricity Consumption',
    category: 'Energy',
    unit: 'kWh / month',
    unitLabel: 'kWh',
    beforeValue: 38500,
    afterValue: 27720,
    differenceValue: -10780,
    differencePercent: -28.0,
    impactVerdict: '28% load reduced via solar offset & VFD pump speed throttling.',
  },
  {
    id: 'imp-water',
    name: 'Freshwater Borewell Extraction',
    category: 'Water',
    unit: 'Litres / month',
    unitLabel: 'Litres',
    beforeValue: 480000,
    afterValue: 196800,
    differenceValue: -283200,
    differencePercent: -59.0,
    impactVerdict: '59% groundwater conserved with closed-loop ultrafiltration & leak repair.',
  },
  {
    id: 'imp-waste',
    name: 'Landfill-Destined Material Scrap',
    category: 'Waste',
    unit: 'kg / month',
    unitLabel: 'kg',
    beforeValue: 3600,
    afterValue: 1440,
    differenceValue: -2160,
    differencePercent: -60.0,
    impactVerdict: '2.16 tonnes/mo yarn scrap diverted to circular recycled yarn spinning.',
  },
  {
    id: 'imp-emissions',
    name: 'Total Scope 1 & 2 Emissions',
    category: 'Emissions',
    unit: 'MT CO₂e / month',
    unitLabel: 'MT CO₂e',
    beforeValue: 41.2,
    afterValue: 23.9,
    differenceValue: -17.3,
    differencePercent: -42.0,
    impactVerdict: '17.3 MT CO₂e monthly reduction from clean solar + boiler economizer.',
  },
  {
    id: 'imp-cost',
    name: 'Net Monthly Operational Utility Cost',
    category: 'Financial',
    unit: '₹ / month',
    unitLabel: '₹',
    beforeValue: 512000,
    afterValue: 338000,
    differenceValue: -174000,
    differencePercent: -34.0,
    impactVerdict: '₹1.74 Lakh monthly utility cost saving (₹20.8 Lakh annualized).',
  },
];

// Mock monthly historical series for chart visualizations
export const MONTHLY_ENERGY_DATA = [
  { month: 'Jan', consumptionKwh: 36200, solarGeneratedKwh: 0, costInr: 325800, targetKwh: 28000 },
  { month: 'Feb', consumptionKwh: 37100, solarGeneratedKwh: 0, costInr: 333900, targetKwh: 28000 },
  { month: 'Mar', consumptionKwh: 39400, solarGeneratedKwh: 0, costInr: 354600, targetKwh: 28000 },
  { month: 'Apr', consumptionKwh: 41200, solarGeneratedKwh: 0, costInr: 370800, targetKwh: 28000 },
  { month: 'May', consumptionKwh: 42800, solarGeneratedKwh: 0, costInr: 385200, targetKwh: 28000 },
  { month: 'Jun', consumptionKwh: 40100, solarGeneratedKwh: 0, costInr: 360900, targetKwh: 28000 },
  { month: 'Jul', consumptionKwh: 38900, solarGeneratedKwh: 0, costInr: 350100, targetKwh: 28000 },
  { month: 'Aug', consumptionKwh: 38500, solarGeneratedKwh: 0, costInr: 346500, targetKwh: 28000 },
];

export const MONTHLY_WATER_DATA = [
  { month: 'Jan', totalLitres: 440000, recycledLitres: 0, leakedEstimateLitres: 38000 },
  { month: 'Feb', totalLitres: 462000, recycledLitres: 0, leakedEstimateLitres: 41000 },
  { month: 'Mar', totalLitres: 495000, recycledLitres: 0, leakedEstimateLitres: 44000 },
  { month: 'Apr', totalLitres: 510000, recycledLitres: 0, leakedEstimateLitres: 46000 },
  { month: 'May', totalLitres: 525000, recycledLitres: 0, leakedEstimateLitres: 48000 },
  { month: 'Jun', totalLitres: 490000, recycledLitres: 0, leakedEstimateLitres: 42000 },
  { month: 'Jul', totalLitres: 475000, recycledLitres: 0, leakedEstimateLitres: 39000 },
  { month: 'Aug', totalLitres: 480000, recycledLitres: 0, leakedEstimateLitres: 40000 },
];

export const WASTE_COMPOSITION_DATA = [
  { name: 'Textile Fabric Scrap', value: 3600, fill: '#10b981' }, // 50%
  { name: 'Industrial Sludge / Dye Res', value: 1850, fill: '#059669' },
  { name: 'Plastic Packing / Polybags', value: 950, fill: '#0d9488' },
  { name: 'Paper & Carton Core Boxes', value: 420, fill: '#14b8a6' },
  { name: 'Organic Canteen Waste', value: 380, fill: '#34d399' },
];

export const EMISSIONS_BY_SOURCE_DATA = [
  { source: 'Grid Electricity (Scope 2)', tonnesCo2e: 31.6, percent: 76.7, color: '#047857' },
  { source: 'Boiler & Diesel Genset (Scope 1)', tonnesCo2e: 6.8, percent: 16.5, color: '#059669' },
  { source: 'Delivery Fleet Transport', tonnesCo2e: 2.4, percent: 5.8, color: '#10b981' },
  { source: 'LPG / Canteen Gas', tonnesCo2e: 0.4, percent: 1.0, color: '#6ee7b7' },
];

export const MOBILITY_EFFICIENCY_DATA = [
  { vehicle: 'Van #1 (Diesel)', mileageKm: 2450, litresUsed: 260, kmPerLitre: 9.4, evPotential: 'High' },
  { vehicle: 'Van #2 (Diesel)', mileageKm: 2680, litresUsed: 290, kmPerLitre: 9.2, evPotential: 'High' },
  { vehicle: 'Van #3 (Diesel)', mileageKm: 2100, litresUsed: 225, kmPerLitre: 9.3, evPotential: 'High' },
  { vehicle: 'Van #4 (Diesel)', mileageKm: 2900, litresUsed: 315, kmPerLitre: 9.2, evPotential: 'High' },
  { vehicle: 'Pickup #5 (Diesel)', mileageKm: 1800, litresUsed: 210, kmPerLitre: 8.6, evPotential: 'Medium' },
  { vehicle: 'Pickup #6 (Diesel)', mileageKm: 1950, litresUsed: 228, kmPerLitre: 8.5, evPotential: 'Medium' },
  { vehicle: 'Utility #7 (Diesel)', mileageKm: 1600, litresUsed: 200, kmPerLitre: 8.0, evPotential: 'Medium' },
  { vehicle: 'Shuttle #8 (Diesel)', mileageKm: 1850, litresUsed: 222, kmPerLitre: 8.3, evPotential: 'High' },
];

export const INITIAL_PREFERENCES: UserPreferences = {
  currency: 'INR',
  measurementUnit: 'Metric',
  emailAlerts: true,
  benchmarkSharing: true,
  theme: 'light',
};
