"""
ClimaCred AI Assistant (floating chat) - Gemini answers grounded in the user's stored data.

    POST /api/ai/chat   {"message": "...", "conversation_id": "..."}
      -> {"answer": "...", "provider": "gemini", "model": "...", "conversation_id": "...", ...}

Rules
-----
1. Every answer is generated by Gemini with a verified model. There are no canned or
   template chatbot answers: if Gemini is not configured, unreachable or failing, the
   response says so explicitly (status + safe message) and ``answer`` is null.
2. The backend gathers the user's stored data itself and sends ONE compact context
   (profile, latest assessment, fingerprint, 5 resource analytics, recommendations,
   latest scenario, plan, impact, stored history) - never a database dump and never
   invented values. With no stored data the context says so, and Gemini is told to
   answer "I don't have your business climate data yet...".
3. Follow-up questions ("How can I reduce it?") work through server-side conversation
   memory keyed by ``conversation_id`` (MongoDB collection ``ai_conversations``).
4. Numbers in the answer are audited against the context. Unverified figures trigger
   one corrective retry; if they remain, the answer is returned with those values
   flagged (never silently).
5. GEMINI_API_KEY never leaves the backend.
"""
from __future__ import annotations

import json
import logging
import re
import uuid
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Tuple

from app.config import settings
from app.database.collections import COLLECTIONS
from app.database.mongodb import get_collection
from app.services import gemini_client
from app.services.gemini_client import GeminiError
from app.services.ai_insight_service import (
    DISCLAIMER,
    INSUFFICIENT_HISTORY,
    STATUS_OK,
    audit_numbers,
    build_context,
    gemini_model_name,
)

logger = logging.getLogger(__name__)

DEFAULT_USER_ID = "default"
CONVERSATIONS = COLLECTIONS["ai_conversations"]
MAX_STORED_TURNS = 40
_CONVERSATION_ID_RE = re.compile(r"^[A-Za-z0-9_-]{8,64}$")

#: Wording required when no business data is stored (Gemini is instructed to use it).
NO_DATA_SENTENCE = (
    "No business data is available yet. Import a business dataset to get climate-specific insights."
)
UNAVAILABLE_VALUE_SENTENCE = "The application does not currently have that value."

#: The starter questions shown in the chat panel.
SUGGESTIONS = [
    "What's my biggest climate risk?",
    "What changed recently?",
    "What should I do next?",
    "Explain my climate score.",
]

CHAT_SYSTEM_PROMPT = f"""You are the ClimaCred AI Assistant for Indian SMEs, embedded in the ClimaCred platform.

Every user message ends with a CONTEXT JSON object. It contains ONLY the user's stored ClimaCred data and values
already calculated by the ClimaCred backend, plus an optional "calculated_answers" block computed by the backend
for this question. Earlier turns of the conversation are included so you can resolve follow-ups.

HARD RULES (never break these):
1. NEVER invent, estimate, guess or extrapolate a number. Every number you write must already appear in CONTEXT
   (including CONTEXT.calculated_answers) or in the conversation. Emissions, savings, investment, payback,
   climate score and percentages come ONLY from the backend values in CONTEXT. If a needed number is missing,
   write "Insufficient data." instead of a number.
2. If CONTEXT.data_state.has_data is false you have NO business climate data. Do not describe or assume any
   business, facility, industry or metric. For any question about the user's business, risks, scores, changes,
   costs or next steps, answer with exactly: "{NO_DATA_SENTENCE}" (you may add one short sentence about how
   ClimaCred works). Greetings and general questions about ClimaCred may be answered normally.
3. Follow-ups: resolve words like "it", "that", "this" using the earlier turns (e.g. after a question about
   water impact, "How can I reduce it?" refers to water).
4. Cost / investment / payback questions: use CONTEXT.selected_scenario, CONTEXT.calculated_answers or the
   investment values in CONTEXT.recommendations. If none contain the value, reply: "{UNAVAILABLE_VALUE_SENTENCE}"
5. Trends / "what changed": compare periods only when CONTEXT.history.resource_changes.available is true;
   otherwise say: "{INSUFFICIENT_HISTORY}". For a question about a recent window ("the last 12 months") use
   CONTEXT.history.last_12_months; for the whole recorded period use CONTEXT.history.resource_changes.
   CONTEXT.history.resource_series holds the actual per-period values (CONTEXT.history.resource_series_source
   says whether they came from an imported monthly dataset or from stored fingerprint snapshots) - quote the
   values that are there, never interpolate between them.
6. Style: short, clear, business-friendly, action-oriented. When it fits: a one-line answer, then "Why:",
   then "What to do next:" (max 3 numbered steps), citing one relevant number from CONTEXT. Plain text only
   (no markdown headers, no code fences, no JSON). Max ~180 words unless the user asks for more detail.
7. Potential savings/payback are catalog-based estimates, not guarantees. Never claim government
   certification, verified carbon credits or guaranteed savings."""


# ---------------------------------------------------------------------------
# Backend calculations used to answer numeric questions (Gemini only explains them)
# ---------------------------------------------------------------------------
_BUDGET_RE = re.compile(
    r"(?:₹|rs\.?|inr)?\s*([0-9][0-9,\.]*)\s*(lakh|lac|lakhs|crore|cr|k|thousand)?",
    re.IGNORECASE,
)
SCENARIO_KEYWORDS = ("what if", "what happens if", "scenario", "simulate", "if i install", "if we install", "switch to", "increase renewable", "add solar")


def _extract_budget_inr(message: str) -> Optional[float]:
    """Extract a budget mentioned in the question, e.g. 'with a ₹10 lakh budget' → 1,000,000 INR."""
    text = message.lower()
    if "budget" not in text and "invest" not in text and "afford" not in text and "spend" not in text:
        return None
    best: Optional[float] = None
    for raw, unit in _BUDGET_RE.findall(text):
        cleaned = raw.replace(",", "").rstrip(".")
        try:
            value = float(cleaned)
        except ValueError:
            continue
        unit = (unit or "").lower()
        if unit in ("lakh", "lac", "lakhs"):
            value *= 100_000
        elif unit in ("crore", "cr"):
            value *= 10_000_000
        elif unit in ("k", "thousand"):
            value *= 1_000
        elif value < 1000:  # bare small number next to "busget"/"invest" is not a budget
            continue
        if value >= 10_000 and (best is None or value > best):
            best = value
    return best


def _recommendations_within_budget(recommendations: List[Dict[str, Any]], budget_inr: float) -> Dict[str, Any]:
    """Greedy, deterministic budget selection from existing recommendation outputs.

    Shortest payback first (highest annual saving per rupee), never exceeding the budget.
    """
    candidates = []
    for rec in recommendations:
        investment = ((rec.get("solution") or {}).get("investmentMinInr")) or 0
        payback = (rec.get("solution") or {}).get("estimatedPaybackPeriodYears")
        savings = (rec.get("solution") or {}).get("potentialAnnualSavingsInr") or 0
        if investment and investment <= budget_inr:
            candidates.append((payback if payback is not None else 99, -savings, rec))
    candidates.sort(key=lambda item: (item[0], item[1]))

    selected: List[Dict[str, Any]] = []
    spent = 0.0
    saved = 0.0
    for payback, _neg_savings, rec in candidates:
        investment = (rec.get("solution") or {}).get("investmentMinInr") or 0
        if spent + investment > budget_inr:
            continue
        spent += investment
        saved += (rec.get("solution") or {}).get("potentialAnnualSavingsInr") or 0
        selected.append({
            "solution_id": rec.get("solution_id"),
            "title": (rec.get("solution") or {}).get("title"),
            "investment_min_inr": investment,
            "estimated_payback_years": (rec.get("solution") or {}).get("estimatedPaybackPeriodYears"),
            "potential_annual_savings_inr": (rec.get("solution") or {}).get("potentialAnnualSavingsInr"),
        })
    return {
        "budget_inr": budget_inr,
        "selected": selected,
        "total_investment_inr": round(spent, 2),
        "total_potential_annual_savings_inr": round(saved, 2),
        "assumption": "Deterministic budget packing by shortest payback using catalog investment minimums; estimates, not guarantees.",
    }


def _scenario_projection(context: Dict[str, Any], message: str) -> Optional[Dict[str, Any]]:
    """Run the existing scenario engine for 'what if' questions (pure engine call)."""
    from app.climate_engine.simulations import simulate_with_fingerprint
    from app.services.profile_service import get_profile
    from app.services.assessment_service import get_assessment
    from app.services.fingerprint_service import get_latest_fingerprint

    profile = get_profile(DEFAULT_USER_ID) or {}
    assessment = get_assessment(DEFAULT_USER_ID) or {}
    fingerprint = get_latest_fingerprint(DEFAULT_USER_ID) or {}
    if not fingerprint:
        return None

    recs = context.get("recommendations") or []
    if not recs:
        return None
    text = message.lower()
    matched_ids = [
        rec["solution_id"] for rec in recs
        if rec.get("title") and any(word in text for word in str(rec["title"]).lower().split() if len(word) > 4)
    ]
    selected_ids = matched_ids[:3] or [rec["solution_id"] for rec in recs[:2] if rec.get("solution_id")]
    if not selected_ids:
        return None
    try:
        result = simulate_with_fingerprint(selected_ids, profile, assessment, fingerprint, scale=100)
    except Exception as exc:  # pragma: no cover - defensive
        logger.warning("Scenario projection for chat failed: %s", exc)
        return None
    return {
        "origin": "backend_scenario_engine",
        "selected_solution_ids": selected_ids,
        "adoption_scale_percent": 100,
        "investment_min_inr": (result.get("investment") or {}).get("min_inr"),
        "annual_savings_inr": result.get("annual_savings_inr"),
        "payback_years": result.get("payback_period_years"),
        "projected_climate_score": result.get("projected_climate_score"),
        "assumptions": (result.get("assumptions") or [])[:4],
    }


def build_chat_context(user_id: str = DEFAULT_USER_ID, message: str = "") -> Dict[str, Any]:
    """Compact structured context for one chat turn (stored data only, no database dumps)."""
    context = build_context(user_id)
    has_data = bool(context.get("data_state", {}).get("has_data"))
    if not has_data:
        return context

    recommendations = context.get("recommendations") or []
    answers: Dict[str, Any] = {
        "note": (
            "All figures below were calculated by the ClimaCred backend from the user's stored data. "
            "Explain them; do not recompute."
        ),
        "recommendations_with_payback": [
            {
                "solution_id": rec.get("solution_id"),
                "title": rec.get("title"),
                "priority": rec.get("priority"),
                "investment_min_inr": (rec.get("investment_range_inr") or [None, None])[0],
                "investment_max_inr": (rec.get("investment_range_inr") or [None, None])[1],
                "estimated_payback_years": rec.get("payback_years"),
                "potential_annual_savings_inr": rec.get("annual_savings_inr"),
                "resource_reduction": rec.get("resource_reduction"),
            }
            for rec in recommendations[:6]
        ],
        "shortest_payback": None,
        "budget_selection": None,
        "scenario_projection": None,
    }
    with_payback = [r for r in answers["recommendations_with_payback"] if r.get("estimated_payback_years") is not None]
    if with_payback:
        answers["shortest_payback"] = min(with_payback, key=lambda r: r["estimated_payback_years"])

    text = (message or "").lower()
    if recommendations:
        if any(word in text for word in ("budget", "invest", "afford", "spend", "lakh", "crore")):
            budget = _extract_budget_inr(message)
            if budget:
                answers["budget_selection"] = _recommendations_within_budget(
                    [_as_recommendation(r) for r in recommendations], budget
                )
        if any(word in text for word in SCENARIO_KEYWORDS):
            answers["scenario_projection"] = _scenario_projection(context, message)
    context["calculated_answers"] = answers
    return context


def _as_recommendation(compact: Dict[str, Any]) -> Dict[str, Any]:
    """Compact context recommendation -> the shape used by the budget packer."""
    low, high = (compact.get("investment_range_inr") or [None, None])[:2]
    return {
        "solution_id": compact.get("solution_id"),
        "solution": {
            "title": compact.get("title"),
            "investmentMinInr": low,
            "investmentMaxInr": high,
            "estimatedPaybackPeriodYears": compact.get("payback_years"),
            "potentialAnnualSavingsInr": compact.get("annual_savings_inr"),
        },
    }


# ---------------------------------------------------------------------------
# Conversation memory (server-side)
# ---------------------------------------------------------------------------
def _valid_conversation_id(value: Any) -> Optional[str]:
    text = str(value or "").strip()
    return text if _CONVERSATION_ID_RE.match(text) else None


def load_turns(conversation_id: str, user_id: str = DEFAULT_USER_ID) -> List[Dict[str, str]]:
    doc = get_collection(CONVERSATIONS).find_one({"user_id": user_id, "conversation_id": conversation_id})
    return list((doc or {}).get("turns") or [])


def _append_turns(conversation_id: str, turns: List[Dict[str, str]], user_id: str = DEFAULT_USER_ID) -> None:
    col = get_collection(CONVERSATIONS)
    now = datetime.now(timezone.utc)
    existing = col.find_one({"user_id": user_id, "conversation_id": conversation_id})
    stored = (list(existing.get("turns") or []) if existing else []) + turns
    stored = stored[-MAX_STORED_TURNS:]
    if existing:
        col.update_one({"_id": existing["_id"]}, {"$set": {"turns": stored, "updated_at": now}})
    else:
        col.insert_one({"user_id": user_id, "conversation_id": conversation_id, "turns": stored,
                        "created_at": now, "updated_at": now})


def delete_conversation(conversation_id: str, user_id: str = DEFAULT_USER_ID) -> bool:
    cid = _valid_conversation_id(conversation_id)
    if not cid:
        return False
    return get_collection(CONVERSATIONS).delete_many({"user_id": user_id, "conversation_id": cid}).deleted_count > 0


def _sanitise_turns(turns: Optional[List[Dict[str, Any]]]) -> List[Dict[str, str]]:
    """Last N turns in a strict user/assistant alternation (Gemini rejects malformed histories)."""
    clean: List[Dict[str, str]] = []
    for turn in turns or []:
        if not isinstance(turn, dict):
            continue
        role = "assistant" if str(turn.get("role")) in ("assistant", "model", "ai") else "user"
        content = str(turn.get("content") or "").strip()[: settings.AI_CHAT_MAX_MESSAGE_CHARS]
        if not content:
            continue
        if clean and clean[-1]["role"] == role:
            clean[-1] = {"role": role, "content": content}  # keep the latest of consecutive same-role turns
        else:
            clean.append({"role": role, "content": content})
    clean = clean[-settings.AI_CHAT_MAX_HISTORY_TURNS:]
    while clean and clean[0]["role"] != "user":
        clean.pop(0)
    if clean and clean[-1]["role"] == "user":
        clean.pop()  # the new question is appended separately
    return clean


# ---------------------------------------------------------------------------
# Gemini request
# ---------------------------------------------------------------------------
def _gemini_chat_payload(context: Dict[str, Any], history: List[Dict[str, str]], message: str,
                         correction: Optional[str] = None) -> Dict[str, Any]:
    contents: List[Dict[str, Any]] = [
        {"role": "model" if turn["role"] == "assistant" else "user", "parts": [{"text": turn["content"]}]}
        for turn in history
    ]
    text = (
        f"{message}\n\n"
        "CONTEXT (the user's stored ClimaCred data + backend-calculated values; use no other numbers):\n"
        f"{json.dumps(context, ensure_ascii=False, default=str)}"
    )
    if correction:
        text += f"\n\nCORRECTION: {correction}"
    contents.append({"role": "user", "parts": [{"text": text}]})
    return {
        "systemInstruction": {"parts": [{"text": CHAT_SYSTEM_PROMPT}]},
        "contents": contents,
        # No temperature override (Gemini 3 defaults); thinking tokens share this budget.
        "generationConfig": {"maxOutputTokens": 4096, "responseMimeType": "text/plain"},
    }


def _audit(answer: str, context: Dict[str, Any], history: List[Dict[str, str]], message: str) -> Dict[str, Any]:
    """Numbers must come from the context, the user's own words or earlier (audited) turns."""
    reference = {**context, "_conversation": [t["content"] for t in history], "_question": message}
    return audit_numbers({"answer": answer}, reference)


def _chat_suggestions(has_data: bool) -> List[str]:  # kept for the suggestions endpoint
    return list(SUGGESTIONS)


async def answer_question(
    message: str,
    conversation_id: Optional[str] = None,
    history: Optional[List[Dict[str, Any]]] = None,
    user_id: str = DEFAULT_USER_ID,
) -> Dict[str, Any]:
    """Answer one chat turn with Gemini, grounded in the user's stored data. Never raises for AI errors."""
    question = (message or "").strip()[: settings.AI_CHAT_MAX_MESSAGE_CHARS]
    if not question:
        raise ValueError("Please type a question.")

    cid = _valid_conversation_id(conversation_id) or uuid.uuid4().hex
    stored = load_turns(cid, user_id)
    turns = _sanitise_turns(stored if stored else history)

    context = build_chat_context(user_id, question)
    has_data = bool(context.get("data_state", {}).get("has_data"))
    base = {
        "provider": "gemini",
        "conversation_id": cid,
        "has_data": has_data,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "suggestions": list(SUGGESTIONS),
        "disclaimer": DISCLAIMER,
    }

    try:
        result = await gemini_client.generate_text(_gemini_chat_payload(context, turns, question))
        answer = result.text.strip()
        audit = _audit(answer, context, turns, question)
        notice = None
        if not audit["verified"]:
            logger.warning("Gemini chat answer contained unverified numbers: %s", audit["unsupported_values"])
            correction = (
                f"Your previous answer contained numbers that are NOT in CONTEXT ({', '.join(audit['unsupported_values'])}). "
                'Rewrite it using ONLY numbers from CONTEXT, or write "Insufficient data." where a number is missing.'
            )
            retry = await gemini_client.generate_text(_gemini_chat_payload(context, turns, question, correction))
            retry_answer = retry.text.strip()
            retry_audit = _audit(retry_answer, context, turns, question)
            if retry_audit["verified"] or len(retry_audit["unsupported_values"]) < len(audit["unsupported_values"]):
                result, answer, audit = retry, retry_answer, retry_audit
            if not audit["verified"]:
                notice = (
                    "Some figures in this answer could not be matched to your stored ClimaCred data: "
                    f"{', '.join(audit['unsupported_values'])}. Treat them as unverified."
                )
    except GeminiError as exc:
        logger.warning("Chat answer not generated: %s (%s)", exc.category, exc.user_message)
        return {
            **base,
            "status": exc.status,
            "answer": None,
            "reply": None,
            "source": None,
            "ai_available": False,
            "model": exc.model or gemini_model_name(),
            "notice": None,
            "error": gemini_client.public_error(exc),
            "message": exc.user_message,
        }

    _append_turns(cid, [{"role": "user", "content": question}, {"role": "assistant", "content": answer}], user_id)
    return {
        **base,
        "status": STATUS_OK,
        "answer": answer,
        "reply": answer,  # backward-compatible alias
        "source": "gemini",
        "ai_available": True,
        "model": result.model,
        "notice": notice,
        "error": None,
        "number_audit": audit,
    }
