import React, { useState, useEffect } from 'react';
import {
  FileText,
  Download,
  Printer,
  ShieldCheck,
  Share2,
  Check,
  Building2,
  Calendar,
} from 'lucide-react';
import { BusinessProfile, ClimateFingerprint, ImpactVerificationMetric, PageId } from '../types';
import { getClimateReport, generateClimateReport } from '../services/api';
import { EmptyState } from '../components/common/EmptyState';
import { FileText as FileTextIcon } from 'lucide-react';

interface ClimateImpactReportPageProps {
  /** null until the user has stored a business profile */
  profile: BusinessProfile | null;
  /** null until a fingerprint has been calculated from stored data */
  fingerprint: ClimateFingerprint | null;
  verificationMetrics: ImpactVerificationMetric[];
  hasAssessment?: boolean;
  onNavigate?: (page: PageId) => void;
}

export const ClimateImpactReportPage: React.FC<ClimateImpactReportPageProps> = ({
  profile,
  fingerprint,
  verificationMetrics,
  hasAssessment = false,
  onNavigate,
}) => {
  const [downloadNotified, setDownloadNotified] = useState(false);
  const [backendReport, setBackendReport] = useState<any>(null);
  const [reportLoading, setReportLoading] = useState(false);
  const [reportError, setReportError] = useState<string|null>(null);
  useEffect(()=> {
    // The stored report is fetched only; nothing is generated on page load.
    setReportLoading(true);
    getClimateReport().then(setBackendReport).catch(()=> setBackendReport(null)).finally(()=> setReportLoading(false));
  }, []);
  const handleGenerateBackendReport = async () => {
    setReportLoading(true);
    setReportError(null);
    try {
      const r = await generateClimateReport();
      setBackendReport(r);
    } catch(e:any){ setReportError(e.message);} finally { setReportLoading(false); }
  };
  const [copiedLink, setCopiedLink] = useState(false);

  const handleDownload = () => {
    setDownloadNotified(true);
    setTimeout(() => {
      window.print();
      setDownloadNotified(false);
    }, 500);
  };

  const handleShare = () => {
    setCopiedLink(true);
    setTimeout(() => setCopiedLink(false), 2500);
  };

  const hasReportData = Boolean(profile?.name) && Boolean(fingerprint);

  if (!hasReportData) {
    return (
      <div className="space-y-8 max-w-3xl mx-auto pb-20">
        <div className="bg-white border border-slate-200/90 rounded-2xl p-6 shadow-xs space-y-2">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-emerald-50 text-emerald-700 flex items-center justify-center">
              <FileTextIcon className="w-4 h-4" />
            </div>
            <h2 className="text-xl font-extrabold text-slate-900 tracking-tight">
              Executive Climate Transformation Report
            </h2>
          </div>
          <p className="text-xs text-slate-600">
            The report is generated by the backend from your stored profile, assessment, fingerprint and verification
            records.
          </p>
        </div>

        <EmptyState
          icon={FileTextIcon}
          title="No report data yet"
          message={
            hasAssessment
              ? 'Your assessment is stored. Add your business profile details and generate the Climate Fingerprint to build the report.'
              : 'Complete your business profile and Climate Assessment to generate a report with real figures.'
          }
          actionLabel="Complete Climate Assessment"
          onAction={() => onNavigate?.('assessment')}
        />
      </div>
    );
  }

  return (
    <div className="space-y-8 max-w-5xl mx-auto pb-20">
      {/* Top Action Header */}
      <div className="no-print bg-white border border-slate-200/90 rounded-2xl p-5 shadow-xs flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <div className="w-8 h-8 rounded-lg bg-emerald-50 text-emerald-700 flex items-center justify-center">
              <FileText className="w-4 h-4" />
            </div>
            <h2 className="text-xl font-extrabold text-slate-900 tracking-tight">
              Executive Climate Transformation Report
            </h2>
          </div>
          <p className="text-xs text-slate-600">
            Summary report prepared from your stored data for board review, green-credit applications and supply chain
            audits.
          </p>
        </div>

        <div className="flex items-center gap-2 w-full sm:w-auto">
          <button
            onClick={handleShare}
            className="flex-1 sm:flex-none px-3.5 py-2 rounded-xl border border-slate-200 hover:bg-slate-50 text-xs font-semibold text-slate-700 flex items-center justify-center gap-1.5 transition-colors"
          >
            {copiedLink ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Share2 className="w-3.5 h-3.5" />}
            <span>{copiedLink ? 'Link Copied' : 'Share Dossier'}</span>
          </button>

          <button
            onClick={handleGenerateBackendReport}
            disabled={reportLoading}
            className="px-3.5 py-2 rounded-xl bg-slate-900 hover:bg-slate-800 text-white font-bold text-xs shadow-xs disabled:opacity-50"
          >
            {reportLoading ? "Generating..." : "Regenerate Live Report"}
          </button>

          <button
            onClick={handleDownload}
            className="flex-1 sm:flex-none px-5 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white font-bold text-xs shadow-md shadow-emerald-600/20 flex items-center justify-center gap-2 transition-all hover:scale-[1.02]"
          >
            <Download className="w-4 h-4" />
            <span>Download PDF Report</span>
          </button>
        </div>
      </div>

      {downloadNotified && (
        <div className="no-print p-3 rounded-xl bg-emerald-50 border border-emerald-200 text-emerald-800 text-xs font-semibold flex items-center gap-2">
          <Printer className="w-4 h-4 text-emerald-600" />
          <span>Generating printable executive PDF view. (Full backend PDF generation will connect to FastAPI in Phase 2).</span>
        </div>
      )}

      {/* Report Document Canvas (Printable Layout) */}
      <div className="bg-white border border-slate-200 rounded-3xl p-8 sm:p-12 shadow-md space-y-10 print:border-none print:shadow-none print:p-0">
        {/* Document Header & Branding */}
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-6 pb-6 border-b border-slate-200">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <div className="w-9 h-9 rounded-xl bg-emerald-600 flex items-center justify-center text-white font-black text-lg">
                C
              </div>
              <span className="text-xl font-extrabold text-slate-900 tracking-tight">
                ClimaCred <span className="text-emerald-600">AI</span>
              </span>
            </div>
            <p className="text-xs text-slate-600 font-semibold tracking-wide uppercase">
              Climate Transformation & Green Investment Intelligence
            </p>
          </div>

          <div className="text-left sm:text-right space-y-0.5 text-xs text-slate-600">
            <p className="font-mono text-slate-900 font-bold">
              Report ID: {backendReport?.report_id || backendReport?.reportId || 'Not generated yet'}
            </p>
            <p className="flex items-center gap-1 sm:justify-end">
              <Calendar className="w-3.5 h-3.5 text-slate-400" />
              <span>
                Report Date:{' '}
                {backendReport?.generated_at || backendReport?.generatedAt
                  ? new Date(backendReport.generated_at || backendReport.generatedAt).toLocaleDateString()
                  : 'Generate the report to date it'}
              </span>
            </p>
            <p className="text-[11px] text-emerald-700 font-semibold">Standard: SME ESG Decarbonization v1.0</p>
          </div>
        </div>

        {reportError && <div className="p-3 rounded-xl bg-amber-50 border border-amber-200 text-amber-800 text-xs">{reportError}</div>}
        {backendReport && (
          <div className="p-4 rounded-xl bg-emerald-50 border border-emerald-200 text-xs space-y-2">
            <p className="font-bold text-emerald-800">Live Backend Report Metadata</p>
            <p className="text-slate-700">Generated: {backendReport.generated_at || backendReport.generatedAt} • Version: {backendReport.calculation_version || backendReport.calculationVersion} • Data Period: {backendReport.data_period || backendReport.dataPeriod}</p>
            <p className="text-slate-700">Data Quality: {backendReport.data_quality?.level || backendReport.dataQuality?.level} ({backendReport.data_quality?.completeness_percent || backendReport.dataQuality?.completeness_percent}% complete)</p>
            <details className="pt-2"><summary className="font-semibold cursor-pointer">Assumptions & Methodology</summary><ul className="list-disc pl-4 mt-1 space-y-1">{(backendReport.assumptions||[]).map((a:string,i:number)=><li key={i}>{a}</li>)}</ul></details>
          </div>
        )}

        {/* Section 1: Business Identification & Executive Summary */}
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <h3 className="text-xs font-bold uppercase tracking-wider text-slate-600 flex items-center gap-1.5">
              <Building2 className="w-4 h-4 text-emerald-600" />
              1. Business Organization & Audit Scope
            </h3>
            <span className="text-xs font-bold px-2 py-0.5 rounded bg-emerald-100 text-emerald-800">
              Verified Audit
            </span>
          </div>

          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 p-5 rounded-2xl bg-slate-50 border border-slate-100 text-xs">
            <div>
              <span className="text-[10px] uppercase text-slate-600 block">Organization</span>
              <span className="font-bold text-slate-900 text-sm">{profile?.name || 'Not recorded'}</span>
            </div>
            <div>
              <span className="text-[10px] uppercase text-slate-600 block">Industry Sector</span>
              <span className="font-bold text-slate-900 text-sm">{profile?.industry || 'Not recorded'}</span>
            </div>
            <div>
              <span className="text-[10px] uppercase text-slate-600 block">Facility Location</span>
              <span className="font-medium text-slate-800 text-xs">{profile?.location || 'Not recorded'}</span>
            </div>
            <div>
              <span className="text-[10px] uppercase text-slate-600 block">Covered Footprint</span>
              <span className="font-bold text-slate-900 text-sm">
                {profile?.facilityAreaSqFt !== null && profile?.facilityAreaSqFt !== undefined
                  ? `${profile.facilityAreaSqFt.toLocaleString()} sq ft`
                  : 'Not recorded'}
              </span>
            </div>
          </div>
        </div>

        {/* Section 2: Climate Readiness & Score Summary */}
        <div className="space-y-4">
          <h3 className="text-xs font-bold uppercase tracking-wider text-slate-600">
            2. Climate Readiness & Diagnostic Summary
          </h3>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 p-6 rounded-2xl border border-slate-200 items-center">
            <div className="flex items-center gap-4">
              <div className="w-16 h-16 rounded-2xl bg-emerald-50 border border-emerald-200 flex flex-col items-center justify-center shrink-0">
                <span className="text-2xl font-black text-emerald-700">{fingerprint?.overallScore ?? '—'}</span>
                <span className="text-[9px] font-bold text-slate-600">/ 100</span>
              </div>
              <div>
                <span className="text-xs font-bold text-slate-900 block">Climate Readiness Rating</span>
                <span className="text-xs text-amber-700 font-bold bg-amber-50 px-2 py-0.5 rounded">
                  {fingerprint?.scoreLabel || 'Not calculated'}
                </span>
                {fingerprint?.benchmarkPercentile !== null && fingerprint?.benchmarkPercentile !== undefined && (
                  <p className="text-[11px] text-slate-600 mt-1">
                    Modelled benchmark percentile: {fingerprint.benchmarkPercentile}
                  </p>
                )}
              </div>
            </div>

            <div className="md:col-span-2 space-y-1.5 text-xs text-slate-600 leading-relaxed">
              <span className="font-bold text-slate-900 block">Calculated Diagnostic Narrative:</span>
              <p>
                {fingerprint?.summaryNote || 'No diagnostic summary stored.'}{' '}
                {fingerprint?.topImprovementDimensions?.length
                  ? `Lowest-scoring dimensions: ${fingerprint.topImprovementDimensions.join(', ')}.`
                  : ''}
              </p>
            </div>
          </div>
        </div>

        {/* Section 3: Dimensional Audit Performance Table */}
        <div className="space-y-4">
          <h3 className="text-xs font-bold uppercase tracking-wider text-slate-600">
            3. Multi-Stream Environmental Audit Scores
          </h3>

          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs border border-slate-200 rounded-xl overflow-hidden">
              <thead className="bg-slate-50 text-slate-600 uppercase tracking-wider font-bold border-b border-slate-200">
                <tr>
                  <th className="py-3 px-4">Resource Dimension</th>
                  <th className="py-3 px-4">Dimension Score</th>
                  <th className="py-3 px-4">Vulnerability Level</th>
                  <th className="py-3 px-4">Identified Root Cause</th>
                  <th className="py-3 px-4">Primary Corrective Opportunity</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {(fingerprint?.dimensions || []).map((dim) => (
                  <tr key={dim.dimension}>
                    <td className="py-3 px-4 font-bold text-slate-900">{dim.dimension}</td>
                    <td className="py-3 px-4 font-mono font-bold text-slate-700">{dim.score}/100</td>
                    <td className="py-3 px-4">
                      <span
                        className={`px-2 py-0.5 rounded-full text-[10px] font-bold ${
                          dim.impactLevel === 'Very High'
                            ? 'bg-rose-100 text-rose-800'
                            : dim.impactLevel === 'High'
                            ? 'bg-orange-100 text-orange-800'
                            : 'bg-emerald-100 text-emerald-800'
                        }`}
                      >
                        {dim.impactLevel}
                      </span>
                    </td>
                    <td className="py-3 px-4 text-slate-600">{dim.primaryCause}</td>
                    <td className="py-3 px-4 text-emerald-800 font-semibold">{dim.improvementOpportunity}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* Section 4: Verified Implementation Impact (Before vs After) */}
        <div className="space-y-4">
          <h3 className="text-xs font-bold uppercase tracking-wider text-slate-600">
            4. Post-Intervention Realized Impact (Telemetry Verification)
          </h3>

          {verificationMetrics.length === 0 && (
            <p className="text-xs text-slate-600">
              No before/after verification has been submitted yet. Impact Verification records appear here once you
              submit real measurements.
            </p>
          )}

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {verificationMetrics.map((met) => (
              <div key={met.id} className="p-4 rounded-xl border border-slate-200 bg-slate-50/50 space-y-2 text-xs">
                <span className="font-bold text-slate-900 block">{met.name}</span>
                <div className="flex items-baseline justify-between text-slate-600">
                  <span>Baseline: {met.beforeValue.toLocaleString()} {met.unitLabel}</span>
                  <span className="font-bold text-emerald-700">Now: {met.afterValue.toLocaleString()} {met.unitLabel}</span>
                </div>
                <div className="pt-2 border-t border-slate-200/80 flex items-center justify-between font-bold">
                  <span className="text-[11px] text-slate-600">Verified Reduction:</span>
                  <span className="text-emerald-700">{met.differencePercent}%</span>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Section 5: Legal & Phase 1 Disclaimer */}
        <div className="p-5 rounded-2xl bg-slate-50 border border-slate-200 text-xs text-slate-600 space-y-1.5">
          <div className="flex items-center gap-1.5 font-bold text-slate-900 uppercase text-[10px]">
            <ShieldCheck className="w-4 h-4 text-emerald-600" />
            <span>Methodology & Scope Disclaimer</span>
          </div>
          <p className="leading-relaxed text-[11px]">
            This report is generated from the operational data you submitted and the platform's configurable emission
            factors and scoring methodology. Figures are modelled estimates, not certified carbon accounting; they are
            not a substitute for ISO 14064 or third-party verified measurement. Verification entries reflect the
            before/after measurements you provide.
          </p>
        </div>

        {/* Signatures Footer */}
        <div className="pt-6 border-t border-slate-200 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-6 text-xs text-slate-600">
          <div>
            <p className="font-bold text-slate-900">{profile?.name || 'Organization'}</p>
            <p className="text-[11px]">Operations & Plant Management Authorization</p>
          </div>
          <div>
            <p className="font-bold text-emerald-800">ClimaCred AI Intelligence Engine</p>
            <p className="text-[11px]">
              Generated {backendReport?.generated_at ? new Date(backendReport.generated_at).toLocaleString() : 'on demand'}
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};
